#!/usr/bin/env python

from argparse import Namespace
import subprocess
import argparse
import re

def running_openvpn() -> None:
    ps = subprocess.run(['ps', '-A'], capture_output=True)
    output = ps.stdout.decode('utf-8')
    m = re.findall('^ *([^ ]+).*openvpn$', output, re.M)
    if len(m) == 0:
        return None
    else:
        return m[0]


def stop(args: Namespace) -> None:
    pid = running_openvpn()
    if pid is None:
        print('openvpn is not running')
        return
    print('kill ', pid)
    subprocess.run(['kill', pid])


def start(args: Namespace) -> None:
    if running_openvpn() is not None:
        print("openvpn is running")
        return

    default_net_addr = '128.129.0'
    is_default_net = False
    while not is_default_net:
        openvpn = subprocess.Popen(['openvpn', args.conf], stdout=subprocess.PIPE)
        route_list = []
        try:
            while openvpn.poll() == None:
                line = str(openvpn.stdout.readline())

                # match net addr
                m = re.findall(r'net_addr_v4_add: ([^ ]+)', line)
                if len(m) != 0:
                    print('openvpn use ip: ', m[0])
                    if default_net_addr not in m[0]:
                        print('openvpn kill for use default ip: ', m[0])
                        openvpn.kill()
                        break
                    else:
                        is_default_net = True

                # match net route
                m = re.findall(r'net_route_v4_add: ([^ ]+)', line)
                if len(m) != 0:
                    print('openvpn add route: ', m[0])
                    route_list.append(m[0])

                # match end
                m = re.search(r'Initialization Sequence Completed', line)
                if m is not None:
                    break

            if is_default_net and args.remove_route:
                for route in route_list:
                    print('openvpn del route: ', route)
                    subprocess.run(['ip', 'route', 'del', route, 'via', '128.129.0.1'])
        except Exception:
            openvpn.kill()

def parse_args() -> None:
    parser = argparse.ArgumentParser(description='Args')
    sub_parsers = parser.add_subparsers(help='sub command')
    
    start_cmd = sub_parsers.add_parser('start', help='start')
    start_cmd.add_argument(
        'conf',
        help='openvpn conf file'
    )

    start_cmd.add_argument(
        '-R',
        '--remove-route',
        action='store_const',
        const=True,
        default=False,
        help='remove route'
    )
    start_cmd.set_defaults(func=start)

    stop_cmd = sub_parsers.add_parser('stop', help='stop')
    stop_cmd.set_defaults(func=stop)

    args = parser.parse_args()
    if args.__contains__('func'):
        args.func(args)
    else:
        parser.print_help()


def main() -> None:
    parse_args()
    
    
if __name__ == '__main__':
    main()
